name: Pull Request
on:
  pull_request:
    types: [opened, labeled, synchronize, reopened]
jobs:
  RunTests:
    runs-on: ubuntu-latest
    steps:
      # Setup
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - uses: ruby/setup-ruby@6e5d382445ae5590b7449d8b3bc8cb1c2c27f617 # v1.317.0
        with:
          bundler-cache: true
      # Test
      - name: Test with rake
        run: bundle exec rake
